### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/Slider#1]
При некоторых значениях "Quantity of scale parts", на шкале слайдера пропадают последние значения. Заметил что при значениях 6 и 14 так происходит, мб еще при каких-то :
![image](https://user-images.githubusercontent.com/25764783/56458086-687c1d80-63ac-11e9-8181-61cfb2cf261c.png)

**Comment by Frolikow** [comment]
При выставленном "Quantity of scale parts" на 10 - если поднимать максимум на 1, то регулярно пропадает последнее число на шкале
![image](https://user-images.githubusercontent.com/25764783/57240647-38de3e00-7059-11e9-9ff5-3d5273b46ca0.png)

на слайдере `"simple"` и `"with-scale"` при изменении минимума или максимума, текущее значение приравнивается _минимуму_. 
на слайдере `"interval"` при при изменении минимума или максимума, текущее значение приравнивается _изначальному значению_. 
на слайдере `"with-step"` значение  минимума или максимума не изменяются дефолтными кнопками инпутов. также как и текущее значение.

По последнему поясню как должно быть:
 минимум должен изменятся  на `stepSize`(это логично)
максимум должен изменятся  на `stepSize`(тоже логично)
а вот у текущего значения поведение должно быть таким:
Если настройки заданы
`minValue = 0; maxValue=19; stepSize=5;`
то возможные значения слайдера должны получиться `0, 5, 10, 15, 19`

**Comment by MorganaLF** [comment]
> то возможные значения слайдера должны получиться 0, 5, 10, 15, 19

А почему здесь 19 должно быть? Ведь если задаем maxValue 19, а оно не кратно 5, то оно должно округлиться до 20? И тогда бегунок идет по значениям 0, 5, 10, 15, 20.

**Comment by MorganaLF** [comment]
> на слайдере "with-step" значение минимума или максимума не изменяются дефолтными кнопками инпутов. также как и текущее значение.

Они изменяются, просто округляются сразу на размер шага (20).

**Comment by Frolikow** [comment]
> > то возможные значения слайдера должны получиться 0, 5, 10, 15, 19
> 
> А почему здесь 19 должно быть? Ведь если задаем maxValue 19, а оно не кратно 5, то оно должно округлиться до 20? И тогда бегунок идет по значениям 0, 5, 10, 15, 20.

Давай попробую примером объяснить)
+ пользователю плагина нужна шкала с минимальным значением 0, и шагом 5, но при этом чтобы максимальное значение было 19 (Он эти значения будет задавать в коде своего сайта),
если будет округлятся, то будет доступно значение 20(в данном случае), чего не должно быть.

Другое дело, когда на демке, в инпутах меняешь значение - то конечно при данных настройках, число 19 никак не может попасться)

**Comment by Frolikow** [comment]
> > то возможные значения слайдера должны получиться 0, 5, 10, 15, 19

 > А почему здесь 19 должно быть? Ведь если задаем maxValue 19, а оно не кратно 5, то оно должно округлиться до 20? И тогда бегунок идет по значениям 0, 5, 10, 15, 20.

 Давай попробую примером объяснить)

 * пользователю плагина нужна шкала с минимальным значением 0, и шагом 5, но при этом чтобы максимальное значение было 19 (Он эти значения будет задавать _в коде_ своего сайта),
  если будет округлятся, то будет доступно значение 20(в данном случае), чего не должно быть.

 Другое дело, когда на демке, _в инпутах_ меняешь значение - то конечно при `minValue = 0;  stepSize=5;`, число 19 никак не может попасться )

Спрашивай еще, если понятно объяснил)

**Comment by Frolikow** [comment]
> > на слайдере "with-step" значение минимума или максимума не изменяются дефолтными кнопками инпутов. также как и текущее значение.
>
> Они изменяются, просто округляются сразу на размер шага (20).

Здесь следует сделать, чтоб при нажатии на дефолтные кнопки инпута, значение менялось на размер шага. Сейчас из-за округления инпуты выглядят сломанными)

**Comment by MorganaLF** [comment]
Исправлено, можно проверить.
