### ISSUE TITLE
Arch

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/Slider#10]
App
слишком занят, апп только собирает вместе все части, больше в нем ничего не происходит,
что то типа 
`app = new Controller(new Model(config), new View(rootNode))`

Controller 
берет на себя задачи view, простое правило - никто кроме view не должен знать что мы в браузере, все обработчики событий, создание\удаление нод - все там

views пока не смотрел, но уже есть вопрос - почему папка views а в ней среди прочего лежит View? не понимаю иерархию

**Comment by MorganaLF** [comment]
> App
слишком занят, апп только собирает вместе все части, больше в нем ничего не происходит

А куда будет лучше перенести публичные методы, необходимые для работы с плагином?

**Comment by MorganaLF** [comment]
> простое правило - никто кроме view не должен знать что мы в браузере

А если у меня модули общаются, генерируя кастомные события на своих элементах, то как контроллер узнает об их событиях?

**Comment by MorganaLF** [comment]
> почему папка views а в ней среди прочего лежит View?

Все views сложила в одну папку в рамках этого ишью https://github.com/MorganaLF/Slider/issues/6

**Comment by alextsk** [comment]
>  генерируя кастомные события на своих элементах

кастомные события - ок, браузерные события - не ок) 
нужны кастомные события - нужен свой event emitter

**Comment by alextsk** [comment]
> А куда будет лучше перенести публичные методы, необходимые для работы с плагином

судя по описанию это работа контроллера

**Comment by alextsk** [comment]
> Все views сложила в одну папку в рамках этого ишью #6 

ок. пусть пока будет, но это странно выглядит)

**Comment by alextsk** [comment]
> судя по описанию это работа контроллера

хотя тут возможно я не прав, может лучше их в апп оставить. 
но не работать напрямую со всеми, нужен какой то интерфейс. либо контроллер должен уметь слушать апп либо кастомные события тут тоже могли бы помочь

и конфиг может вынести в свой модуль, конфиг это часть модели по идее

**Comment by MorganaLF** [comment]
> но не работать напрямую со всеми, нужен какой то интерфейс

Имеется ввиду, что из апп нельзя напрямую вызывать методы модели, вью, контроллера?

**Comment by alextsk** [comment]
>  либо контроллер должен уметь 

контроллера можно, если выбрать такую реализацию

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
mainViewConfig  - а зачем еще один конфиг? я думаю есть один конфиг приложения, просто удобнее его хранить в модели, т.к. логически это первое состояние. а вью рисуется на основании модели, т.е. html = view(model). 
например события меняют модель, потом вью отрисовывает измененную модель, не смотрел еще  так ли оно, но надеюсь что так)

_createModelInstance - внутри присваивает в модель и опять результат в модель? лишняя обертка мне кажется, с вью то же самое

**Comment by MorganaLF** [comment]
> mainViewConfig - а зачем еще один конфиг? 

А если это опции, которые исключительно с отображением связаны? Например, вертикальный/горизонтальный вид ведь никак с моделью не связан?

**Comment by alextsk** [comment]
не очень понимаю, все опции связаны с отображением, у нас же плагин в браузере) stepSize и  maxValue не влияют на отображение?

**Comment by MorganaLF** [comment]
Я имею ввиду, что мне казалось, что минимум, максимум, размер шага и текущее значение слайдера имеют отношение к бизнес-логике, а вот вертикальный он или горизонтальный, красный или зеленый - это уже исключительно дело вью.

**Comment by alextsk** [comment]
бизнес-логика - это все что меняет модель, если ты хранишь стейт вертикально-горизонтально или цвет - это просто еще одна модель, вью вообще ничего не должна хранить, она только рисует.

вообще это зависит от задачи, может быть вообще все состояние зашито в модели, может быть какие то элементы будут только во вью, если нам не интересно их состояние(анимашечки). 
но если мы явно выставляем начальное состояние какого-то параметра то скорее всего имеет смысл его и дальше изменять явно, вдруг понадобится через апи узнать вертикальность.

**Comment by MorganaLF** [comment]
Понятно, переделаю)

**Comment by alextsk** [comment]
Апп, если он отдельный класс, может общаться только с контроллером. 
по большому счету он и есть контроллер, тут тебе решать - может вся работа уйти в Controller и апп будет файл  из трех строчек собирающий приложение, но если ты считаешь что нужен отдельный слой для апи(может контроллер слишком сложный и хочется выделить юзер интерфейсы) - ок, однако тогда он не работает напрямую с вью и моделью, а заказывает это контроллеру.

не уверен понятно ли написал, если что  - спрашивай

**Comment by alextsk** [comment]
private updateView(): void {
    this.controller.destroy();
    this.createViewInstance();
    this.controller = new Controller(this.view, this.model);
    this.controller.initRangeValues();
  }
вот например, всего этого юзер интерфейс делать не должен, он даже не уверен нужно ли что нибудь апдейтить, он может только попросить controller.onSetHorizontal() или .onSetDirection('horizontal') или событие послать, а нижние слои сам решают нужно ли что-то делать, может они уже в нужном состоянии, может там троттл, чтоб каждые 10мс не перерисовываться и тд.

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
теперь из кода Апп видно, что не особо он и нужен, все методы мапятся 1 к 1 на контроллер. наверно пока так можно, недолго удалить его если что. 
а ты как считаешь - нужен этот отдельный слой?

```
const isRunnersAtTheEndOfSlider = this.model.type === 'interval'
      && this.model.startValue === this.model.maxValue;
сonst isRunnersAtTheStartOfSlider = this.model.type === 'interval'
      && this.model.endValue === this.model.minValue;
```
странно что контроллер этим занимается
```
 const isEndValueChanging = eventType === 'changeendvalue' && this.model.type === 'interval'
      || eventType === 'setendvalue' && this.model.type === 'interval';
```
и этим
```
    const isClickNearByStartRunner: boolean = this.model.type === 'interval'
      && (Math.abs(value - this.model.startValue)
      > Math.abs(value - this.model.endValue)
```
тут вообще математика)

контроллер должен только связать модель и вью, все расчеты кто куда кликнул и где бегунки они должны делать сами, а контроллеру сообщения слать о результатах. а он на основе сообщений определит у кого какие методы вызвать, (или тоже сообщения послать, зависит от реализации) сейчас получается он за них доделывает работу

**Comment by MorganaLF** [comment]
> теперь из кода Апп видно, что не особо он и нужен

Мне показалось, что так удобнее оборачивать потом код в jquery-плагин, я создаю в нем только экземпляр App и обращаюсь к его же методам.

**Comment by alextsk** [comment]
а так ты создашь экземпляр контроллера, кроме этого ведь ничего не поменяется?

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
https://github.com/MorganaLF/Slider/blob/79732a4625ed135cb1234ba82932741370754f54/src/plugin/Controller/Controller.ts#L132-L140
 почему такое выравнивание?

https://github.com/MorganaLF/Slider/blob/79732a4625ed135cb1234ba82932741370754f54/src/plugin/Controller/Controller.ts#L43
https://github.com/MorganaLF/Slider/blob/79732a4625ed135cb1234ba82932741370754f54/src/plugin/Controller/Controller.ts#L48
 лучше не присваивать данные прямо в поле, и не получать их, поля должны быть приватные а доступ через публичные методы

https://github.com/MorganaLF/Slider/blob/79732a4625ed135cb1234ba82932741370754f54/src/plugin/Controller/Controller.ts#L175
очепятка) и может как то переформулировать? не очень понятно. я даже прочитав код не уверен что понял, можешь объяснить что она делает?

**Comment by MorganaLF** [comment]
> очепятка) и может как то переформулировать? не очень понятно. я даже прочитав код не уверен что понял, можешь объяснить что она делает?

Здесь, в случае, если слайдер интервальный, и в модель приходит запрос на установление какого-то произвольного текущего значения (в данном случае приходит из шкалы), то в зависимости от того, к какой границе новое значение ближе, ту границу мы и двигаем. То есть если пользователь на шкале ткнул ближе к левому бегунку, то должен двигаться левый бегунок, а не правый. 

А в названии переменной я пыталась написать "Находится ли устанавливаемое значение рядом с начальной границей"

**Comment by alextsk** [comment]
теперь понятно. а почему модель внутри себя не может это определить?

**Comment by MorganaLF** [comment]
Ну у меня сейчас когда происходит клик на Scale, контроллер наблюдает, перехватывает приходящее значение Value и уже с этим значением вызывает соответствующий метод Model. Или нужно напрямую сделать наблюдателем Модель, без участия контроллера?

**Comment by alextsk** [comment]
нет, это нормально что он наблюдает, но не за кликом а за вью

произошло событие во вью 
-> вью сообщило контроллеру, но без подробностей, зачем ему знать про шкалу, достаточно что есть запрос на установку значения 
-> контроллер сообщил модели что есть запрос на установку значения, но неизвестно какого, 
-> модель внутри себя тогда вычисляет чье это значение по твоей формуле
-> модель сообщает контроллеру что есть изменения в стейте
-> контроллер просит вью отрисовать новый стейт модель

**Comment by alextsk** [comment]
есть варианты MVC где эта схема по-другому работает - где то вью слушает модель напрямую, где то модель вызывает методы вью, и тд, любые направленные графы на трех узлах) 
я так подробно расписал чтобы точно убедиться что мы одну архитектуру представляем) если нет - расскажи свой вариант

**Comment by MorganaLF** [comment]
Сейчас получилось так: 
- вью сообщило контроллеру, что нужно установить такое-то value.
- контроллер вызвал метод модели на установку этого значения.
- модель сама определила, какое именно значение ей надо менять
- модель послала сообщение
- контроллер поймал сообщение и попросил вью обновиться.

Вроде, об одной и той же реализации говорим)

**Comment by alextsk** [comment]
> зачем ему знать про шкалу

observeClickOnScale - вью-специфично, там может шкала принять форму круга например, не заводить же новый метод

**Comment by MorganaLF** [comment]
Переименовала только в контроллере. Вью ведь может внутри себя знать, что у него есть шкала, бегунки и т.д.?

**Comment by alextsk** [comment]
> Вью ведь может внутри себя знать,

конечно, если не вью то кто)

**Comment by MorganaLF** [comment]
Объединила, что смогла, остальное, мне кажется, туда никак не подходит)

**Comment by alextsk** [comment]
да, норм.
