### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/Slider#11]
Model
_validateConstructorOptions - валидатор только проверяет, если он исправляет он уже не совсем validate, и имена _check... тоже вводят в заблуждение 

(кстати, начинать имена с _  в ts необязательно, они явно объявлены как private)

 this[valueKeyName] = 100; хардкод, почему именно 100? по хорошему это должно приходить из конфига, ну или если есть причина, то хотя бы их констант

(isDefaultValueFromKeyHundred) хардкод на уровне имен - всегда плохая идея

isEndValueExceedsStartValue оно желательно exceeds, тут наверное что то другое имелось ввиду)

[key: string]: any; - зачем? возможны новые поля?

valueKeyName: string - ключи ведь известны, можно уточнить тип как юнион литералов, типа `'a' | 'b' | ...`, почему кстати такое решение? может передать само значение? this.x = this.fn(this.x)

**Comment by MorganaLF** [comment]
> может передать само значение? this.x = this.fn(this.x)

Пример не поняла)

Решение такое было, чтобы можно было не дублировать код и не писать одно и то же для 

`this.startValue = (this.maxValue - this.minValue) / ratio + this.minValue`
`this.endValue = (this.maxValue - this.minValue) / ratio + this.minValue`

а просто передать ключ и применить к соответствующему свойству метод.

**Comment by MorganaLF** [comment]
> [key: string]: any; - зачем? возможны новые поля?

Без этого TS ругается на переменную в ключе. 

![777](https://user-images.githubusercontent.com/38564412/58431750-f6d47500-80b7-11e9-8fc3-315612bbd270.png)

**Comment by alextsk** [comment]
в _checkNumber например выставляются 3 значения в 0 и 2 в 100, есть причина их не выставить просто напрямую? 
this.startValue = 0; или если нужны проверки  this.startValue = this.checkIfNumberAndUpdate(0)

если я правильно понял намерение)

> Без этого TS ругается на переменную в ключе.

тут юнион должен помочь, а индекс это то же самое что any

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
```
const isEndValueGoesBeyondStartValue: boolean = (this.endValue < this.startValue)
const isStartValueGoesBeyondEndValue: boolean = (this.startValue > this.endValue)
```
в чем разница? 
c isEndValueExceedsStartValue  я похоже не заметил что это одно условие
что делает checkAndFixIntervalValues и почему она возвращает boolean?
может общее условие вынести и назвать как нибудь boundsInWrongOrder

много fix и value в именах, если у фикс есть значение - починить, (не уверен что это оправдано, но намерение понятно), то значение value-"значение", т.е. новую информацию оно редко дает: Value, Data, Info относятся почти к любым данным, это как к каждой функции дописывать Function. 

посмотри на имена, может где то прояснить назначение, а где то дописать код
fixToNumber - необязательно вернет число, что отдаст isNaN(true)? isNaN("")?
fixToValueMultipleOfStep - alignToStep,
fixCurrentValue - почему оно сломалось? надо читать код метода. clampBetweenBounds или Edges мне кажется сразу объясняет что происходит
reminderOfStepSlider - проверь в словаре) и почему слайдер, мы же в модели
calculateRoundedValue - зачем? если кроме math.round ничего не происходит
calculateCoefficient - коэффициент чего?
и тд

но все подряд не зачищай, иногда и value уместно, 
```
      eventType,
      value: this.calculateRoundedValue(value),
```
вот тут например, есть тип а есть значение - все понятно

**Comment by MorganaLF** [comment]
Исправлено

**Comment by MorganaLF** [comment]
> reminderOfStepSlider - проверь в словаре) и почему слайдер, мы же в модели

Здесь имелся ввиду остаток от деления, вроде он reminder и называется)

**Comment by alextsk** [comment]
reminder - напоминатель, возможно тебе нужен remainder)

**Comment by MorganaLF** [comment]
Точно, несколько раз читала, и не заметила ошибку) Но в этот раз правильно написала в переменной)

**Comment by alextsk** [comment]
пока сильно не было времени посмотреть, но навскидку:

divisionRemainderOfInterval - это понятно что остаток, и раньше было понятно, % же видно. хорошо когда из названия понятен смысл а не просто операция.

isBoundsInWrongOrder - are, множественное же. кстати, где то Bounds где то Edges, это одни и те же сущности? если да, может что-то одно выбрать? я за edges, bounds - сокращение от boundaries и иногда как глагол выглядит

fix...- все же не очень, может normalize?

**Comment by MorganaLF** [comment]
> где то Bounds где то Edges, это одни и те же сущности? 

Edges я использовала для обозначения краев min и max, а bounds для обозначения границ выбранного интервала.

**Comment by alextsk** [comment]
тогда ок. naming is hard)

**Comment by MorganaLF** [comment]
Исправлено
