### ISSUE TITLE
API

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/Slider#12]
вопрос:
 ```
$(item).customSlider({ elementIndex });
$(item).customSlider('addChangeValueObserver', observeChangeValue);
```
чтобы инициализировать слайдер нужно два раза вызывать его?
и почему клиентский код знает про его внутренние события?
с апи надо еще поработать

от elementIndex надо избавляться, во втором задании в мелком компоненте это еще как то работало, но тут уже не поддерживаемо

**Comment by MorganaLF** [comment]
> и почему клиентский код знает про его внутренние события?

Здесь мне понадобилось добавить плагину публичный метод `addChangeValueObserver`, чтобы пользователь при необходимости мог подписаться на изменение текущих значений слайдера и делать что-то, что ему необходимо. Например, апдейтить инпуты, это ведь не входит в функционал самого плагина.

На инициализацию плагина это никак не влияет, плагин инициализируется строкой `$(item).customSlider({ elementIndex });`, а дальше идет просто отдельный вызов метода.

**Comment by MorganaLF** [comment]
Изначально я для примера себе взяла API Slick

![Безымянный](https://user-images.githubusercontent.com/38564412/59690134-8d90df00-91e9-11e9-9352-d4873e35e136.png)

https://kenwheeler.github.io/slick/

, но так как модель не может знать о DOM, это пришлось изменить, и получилось то, что 
получилось сейчас)

**Comment by MorganaLF** [comment]
От elementIndex избавилась, про подписку пользователем на события пока непонятно)

**Comment by alextsk** [comment]
addChangeValueObserver - не похож на метод, это выглядит как конструктор перегруженный по типу аргумента. 

у слика понятно что это событие

> In slick 1.4, callback methods have been deprecated and replaced with events. 

можно сделать точно наоборот)

я бы как юзер ожидал что то типа
`let slider = $("sliderElement").slider(options)`
а потом
`slider.addEvent(callback)`
или 
`slider.on("event", callback)`

но первый вариант и проще типизируется и ide подскажет какие есть варианты

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
```
  if (typeof options === 'string') {
    return $this.data('constructor')[options](...args);
 ```
а это еще нужно?

`name: 'changevalue' | 'changebound',`
changebound где нибудь используется?
а что будет если вызвать changevalue а отдать ему  колбэк с changeBoundCallbackSettings ?

`readonly changeBoundObserver = this.observeBoundChanging.bind(this);`
чтобы так не делать нужно использовать декораторы

**Comment by MorganaLF** [comment]
```
if (typeof options === 'string') {
    return $this.data('constructor')[options](...args);
```

> а это еще нужно?

Ну так у меня все публичные методы таким образом вызываются: 

```
$element.customSlider('getMinValue');
$element.customSlider('getStepSize');
$element.customSlider('setStepSize', 5);
```

Это же вроде бы best practices в jQuery плагинах, или нет?)

**Comment by MorganaLF** [comment]
> changebound где нибудь используется? 

Нигде не используется, а вдруг будет? А вот как разделить коллбеки, пока не придумала, только если два отдельных метода заводить? `addChangeValueEvent, addChangBoundEvent. `

**Comment by alextsk** [comment]
> Это же вроде бы best practices в jQuery плагинах, или нет?)

я такого не видел, но я не спец по джквери) вообще явное всегда лучше неявного, есть причина просто метод не объявить?

**Comment by alextsk** [comment]
>  А вот как разделить коллбеки, пока не придумала, только если два отдельных метода заводить

я же выше так и предлагал

а разделить можно как алгебраический тип ( в доках это Discriminated Unions), или через какие нить условные типы, тут надо подумать. с методами думать не надо)

**Comment by alextsk** [comment]
> Нигде не используется, а вдруг будет?

так можно много всего написать)

**Comment by MorganaLF** [comment]
Ну вот, например, в jQuery UI все методы вызываются таким же способом:

http://api.jqueryui.com/slider/#method-destroy

Поменять, по-идее, должно быть не сложно, вопрос только в том, соответствует ли это требованиям задания, где говорилось придерживаться best practisec.

**Comment by MorganaLF** [comment]
> я же выше так и предлагал
а разделить можно как алгебраический тип ( в доках это Discriminated Unions), или через какие нить условные типы, тут надо подумать. с методами думать не надо)

Тогда я просто сделаю один метод addChangeValueEvent, а второй опущу за ненадобностью)

**Comment by alextsk** [comment]
> Ну вот, например, в jQuery UI все методы вызываются таким же способом:

хм, тогда пока оставь, я уточню что имелось ввиду, может когда то это и было бест практис) 
а может там какие то свои причины так делать

**Comment by alextsk** [comment]
> а может там какие то свои причины так делать

оказывается есть)
они нужны чтобы не ломать чейнинг и не замусоривать неймспейс. 

через методы думаю можно это сделать так `slider(initOptions).slider.method1('''')` например, если методы возвращают джквери элемент. т.е. получится каждый метод как миниплагин

но и первый вариант с точки зрения джквери был легален, тут я не разобрался сразу. 

решили что можно оставить любой вариант, какой логичнее по твоему

**Comment by MorganaLF** [comment]
> решили что можно оставить любой вариант, какой логичнее по твоему

Ну мне кажется, что первый проще и нагляднее, к тому же мне он уже был привычен - встречался в других jQuery плагинах. Так если я оставлю этот способ, то мне и подписку пользователем на ивенты вернуть, как было? То есть, что-то вроде:

`$(element).customSlider('addEvent', function)?`

**Comment by alextsk** [comment]
можно так, можешь вобще джкверишный on, только на события повесить еще неймспейс ('customSlider.onEvent')

но чтобы два раза не вызывать можно подписываться на события при инициализации 
slider({opt1: '12',..., onEvent(){...}, ...})

**Comment by MorganaLF** [comment]
> можешь вобще джкверишный on

С .on не получится, он вешает события на элемент, а в данном случае событие генерирует модель, и ни она, ни контроллер не должны знать про dom.

**Comment by MorganaLF** [comment]
> readonly changeBoundObserver = this.observeBoundChanging.bind(this);
чтобы так не делать нужно использовать декораторы

Пыталась с декораторами, но ничего не вышло. Если мне нужно добавить в наблюдатели функцию с сохранением контекста, мне все равно надо в какую-то переменную ее записать, а иначе ее потом никак не удалить из наблюдателей. Выходит по сути то же самое, что без декоратора. Выкладываю пока, что получилось, вариант не рабочий, как исправить, не понимаю)

**Comment by MorganaLF** [comment]
Например: 

```
this.scale.observableSubject.addObserver(
        this.bind(this.dispatchClickOnScale, this),
      );
```

Через какое-то время

```
 this.scale.observableSubject.removeObserver(
        this.bind(this.dispatchClickOnScale, this),
      );
```

Мне ведь все равно придется куда-то сохранять результат, который возвращает декоратор, чтобы потом удалить его из списка наблюдателей?

**Comment by alextsk** [comment]
makeSliderMethod- создает или вызывает?

**Comment by alextsk** [comment]
> С .on не получится, он вешает события на элемент - 

на обертку джквери. по идее сам плагин для слайдера длжен быть внешним кодом и работать с его апи. т.е. события снаружи плагина и события внутри самого слайдера - это разные типы событий. код снаружи не должен иметь возможность вызвать события в модели напрямую

**Comment by MorganaLF** [comment]
Установила из npm bind-decorator. 
В паре мест оставила bind, поскольку он тут использовался для передачи в метод помимо объекта event других параметров:

```
$textInput.on(textInputChange, this.handleTextInputChange.bind(this, methodName));
$checkbox.on(checkboxChange, this.handleCheckboxChange.bind(this, onMethodName, offMethodName));
```

В остальном по проекту вроде больше ничего не осталось, где можно было бы применить декоратор.

**Comment by MorganaLF** [comment]
> makeSliderMethod- создает или вызывает?

Вызывает метод и возвращает результат. Наверное, это должно называться как-то callSliderMethodAndReturnResult?)

Вообще, я смотрела на 3 пункт стандартов по JS, но видимо я его совсем не так поняла:

> Функции высшего порядка, возвращающие функции, следует именовать по шаблону make + .* + отглагольное существительное, где .* — опциональный, синтаксически корректный набор слов уточняющий предназначение функции. Например, makeButtonClickHandler.

**Comment by alextsk** [comment]
> callSliderMethodAndReturnResult

просто сменить make на call)

> Функции высшего порядка

но ведь makeSliderMethod не возвращает функцию. он возвращает число(почему?) а потом происходит такой трюк `const makeSliderMethod: any = this.makeSliderMethod;` 
может он сразу будет возвращать any? вроде это логично для метода вызывающего что угодно

**Comment by MorganaLF** [comment]
Исправила. Теперь на событие "changvalue" снаружи можно подписаться двумя способами, либо передав коллбек сразу в параметры слайдера при инициализации 

`$slider.customSlider({ onChangeValue: this.updateInputValues });`

Либо подписавшись при помощи .on:

` $slider.on('changevalue', function(){});`
