### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/Slider#4]
По бэму, на блоках не должно быть маргинов и паддингов. Если нужно спозиционировать блок, то его нужно либо положить в элемент-обертку и позиционировать обертку, либо подумать можно ли данный блок сделать элементом ближайшего родительского блока.
Я про вот этот блок: 
![image](https://user-images.githubusercontent.com/25764783/57007422-bf86bb80-6c12-11e9-9f36-658e7a04822f.png)

**Comment by MorganaLF** [comment]
Но здесь ведь это только маржинов касается? Паддинги тут не внешнее позиционирование определяют, а внутренние отступы самого инпута.

**Comment by Frolikow** [comment]
Верное замечание))

Дальше идем, тут у тебя стили одного блока определены в стилях другого ( [стандарты-бэм-пункт4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md))
```stylus
.demo-page
  &__content
    max-width 1200px
    margin 0 auto

  &__row
    display flex
    align-items center

    +md()
      flex-wrap wrap

  &__column
    padding 20px

    &_with-options
      flex-grow 1

      +md()
        order -1

    .slider
      width: 500px

      +md()
        width 100%

    .slider_vertical
      margin 0 50px
      width auto

    +md()
      width 100%
```
И здесь же дополню, в стилях следи за пунктацией (в данном случае `:`). Если не пишешь нигде, то старайся чтоб в правилах нигде не встречалось. То же касается `;`

**Comment by MorganaLF** [comment]
Готово

**Comment by Frolikow** [comment]
Хорошо, еще с пунктуацией поправь в паре мест, и можно закрывать)

**Comment by MorganaLF** [comment]
Надеюсь, больше ничего не пропустила)
