### ISSUE TITLE
SliderModel, SliderModelOptions, SliderController

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/Slider#6]
В контексте плагина Slider, добавление имени плагина при именовании излишне. Model, ModelOptions, Controller, несут в себе столько же смысла. 
И думаю будет лучше, сделать все вьюхи в папке views, например. Получатся папки: Model,Controller, App и views(со всеми вьюхами).

**Comment by Frolikow** [comment]
> Все views сложила в одну папку в рамках этого ишью #6

Мы с Алексеем подумали на счет именования, которое я предлагал. Пришли к выводу что оно не очень правильное.
Решили что назвать общую папку `View` будет логичнее. А папку `View`, которая сейчас со всеми вьюхами лежит, лучше переименовать в `MainView`.

Таким образом получим папки `Model View Controller`, и снаружи все вьюхи будут выглядеть как `View`, как и ожидается что будет единственная вьюха(и не важно на сколько частей она разбита внутри)

**Comment by MorganaLF** [comment]
Исправлено
