### ISSUE TITLE
Зависимость слайдеров

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/Slider#7]
Сейчас в твоей реализации слайдеры работают независимо только за счет модификаторов.
Если я например, захочу сделать эквалайзер из твоих слайдеров? Мне точно понадобятся **одинаковые** слайдеры, т.е. в данном случае, с одинаковыми модификаторами. 
Но в таком случае все слайдеры получатся полностью зависимы друг от друга. При изменении одного-будут меняться все. 
Суть в том, что каждый слайдер должен быть полностью не зависим. Для каждого слайдера логика должна по своему отрабатывать.
Попробуй во второй слайдер прокинуть `{ modifier: "simple" }`, как на первом слайдере. И проверь как они станут работать, и что при этом происходит с остальными слайдерами и всеми инпутами на странице

**Comment by MorganaLF** [comment]
Поправила.
