### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/Slider#9]
а как рассчитывается шкала и передвижение по шагам?
![image](https://user-images.githubusercontent.com/16453186/58087249-5e874d80-7bea-11e9-9d47-cae83986f597.png)
![image](https://user-images.githubusercontent.com/16453186/58087276-719a1d80-7bea-11e9-8727-90b25a1ce682.png)

тут можно выбрать два варианта ни один из которых не совпал со шкалой)

**Comment by MorganaLF** [comment]
> тут можно выбрать два варианта ни один из которых не совпал со шкалой)

А как это должно выглядеть? У меня деления шкалы ставятся в зависимости от произвольного числа, которое указано в настройках шкалы.  На втором слайдере есть поле "Quantity of scale parts".

А если ставить метки шкалы в зависимости от размера шага, то при размере шага 1 получится, что цифры шкалы будут налеплены друг на друга.

**Comment by alextsk** [comment]
конечно от размера шага, более того при нажатии на цифру надо перемещать бегунок на нее, сейчас это не получится сделать.

> то при размере шага 1 получится, что цифры шкалы будут налеплены друг на друга

значит такова воля юзера) может у него всего 5 значений и не будут налеплены

и все же почему их два разных с одним шагом?

**Comment by MorganaLF** [comment]
> и все же почему их два разных с одним шагом?
Здесь мне, видимо, надо переделать расчет шага. У меня когда бегунок находится в конце слайдера, в обратном направлении отсчитывает размер шага, и в случае, если в конце оставшийся кусок не был кратен шагу, получается, что значения не совпадают. Я это уже изменила, запушу вместе с исправлениями шкалы.

**Comment by MorganaLF** [comment]
Вопрос по поводу шкалы. Допустим, в настройках слайдера пользователь установил минимальное значение 0, максимальное 100, а размер шага 11. Как в таком случае быть со шкалой, нужно ли на ней рисовать последнее значение 100 и где его размещать?

![123456](https://user-images.githubusercontent.com/38564412/58163473-c1c9bc00-7c8c-11e9-912a-aa0eb1e87896.png)

**Comment by alextsk** [comment]
тут есть разные мнения)
я считаю нужно, размещать в конце, и на него можно попасть, граничные значения всегда активны. 
расстояние от предпоследнего до последнего может быть не равно другим расстояниям. в твоем примере 99 и 100 склеятся, это нормально
другой вариант - не показывать, тут все просто но неочевидно для пользователя

в любом случае, если мы попали на последний не должно изменяться множество значений, оно всегда (minVal, minVal+step, minVal+step+step, .... maxVal), т.е. статично и растет снизу

**Comment by MorganaLF** [comment]
Исправлено

**Comment by alextsk** [comment]
уже почти хорошо, небольшой косячок -
![image](https://user-images.githubusercontent.com/16453186/58246991-c375ab80-7d82-11e9-8f13-fd5e0dc27681.png)
при некратном шаге не срабатывает клик на макс значении

**Comment by MorganaLF** [comment]
Исправлено
